#############################################################################
# Makefile for building: GrxMenu
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  GrxMenu.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile GrxMenu.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBENGINEWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB
CFLAGS        = -fpermissive -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -fpermissive -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/lib -I/usr/lib/x86_64-linux-gnu -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebChannel -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtPositioning -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = GrxMenu1.0.0
DISTDIR = /home/alberto/git/GrxMenu/.tmp/GrxMenu1.0.0
LINK          = g++
LFLAGS        = -fpermissive -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) -lssh2 -lldap -lcrypto -lssl -lsqlite3 -lQt5WebEngineWidgets -lQt5PrintSupport -lQt5Widgets -lQt5WebEngineCore -lQt5Quick -lQt5Gui -lQt5Sql -lQt5WebChannel -lQt5Qml -lQt5Network -lQt5Positioning -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		botonera/botonera.cpp \
		configuracion/configuracion.cpp \
		soporte/nmap_xml.cpp \
		sedes/sedes.cpp \
		soporte/soporte.cpp \
		soporte/equipos.cpp \
		soporte/ejecutahilo.cpp \
		soporte/tabescaner.cpp \
		basedatos/basedatos.cpp \
		mame/mame.cpp \
		usuarios/hilousuarios.cpp \
		usuarios/clase_ldap.cpp \
		usuarios/usuario.cpp \
		usuarios/form_grupos.cpp \
		usuarios/form_usuarios.cpp \
		configuracion/simplecrypt.cpp \
		tunel.cpp \
		lib/lib.cpp \
		lib/globals.cpp \
		soporte/paginaweb.cpp \
		mailing/mailing.cpp \
		mailing/sqlquerymodel.cpp \
		acercade/acercade.cpp \
		soporte/usuarios.cpp \
		configuracion/buscarou.cpp qrc_iconos.cpp \
		moc_botonera.cpp \
		moc_configuracion.cpp \
		moc_sedes.cpp \
		moc_soporte.cpp \
		moc_equipos.cpp \
		moc_ejecutahilo.cpp \
		moc_tabescaner.cpp \
		moc_basedatos.cpp \
		moc_mame.cpp \
		moc_hilousuarios.cpp \
		moc_form_usuarios.cpp \
		moc_form_grupos.cpp \
		moc_tunel.cpp \
		moc_paginaweb.cpp \
		moc_mailing.cpp \
		moc_sqlquerymodel.cpp \
		moc_acercade.cpp \
		moc_usuarios.cpp \
		moc_buscarou.cpp
OBJECTS       = main.o \
		botonera.o \
		configuracion.o \
		nmap_xml.o \
		sedes.o \
		soporte.o \
		equipos.o \
		ejecutahilo.o \
		tabescaner.o \
		basedatos.o \
		mame.o \
		hilousuarios.o \
		clase_ldap.o \
		usuario.o \
		form_grupos.o \
		form_usuarios.o \
		simplecrypt.o \
		tunel.o \
		lib.o \
		globals.o \
		paginaweb.o \
		mailing.o \
		sqlquerymodel.o \
		acercade.o \
		usuarios.o \
		buscarou.o \
		qrc_iconos.o \
		moc_botonera.o \
		moc_configuracion.o \
		moc_sedes.o \
		moc_soporte.o \
		moc_equipos.o \
		moc_ejecutahilo.o \
		moc_tabescaner.o \
		moc_basedatos.o \
		moc_mame.o \
		moc_hilousuarios.o \
		moc_form_usuarios.o \
		moc_form_grupos.o \
		moc_tunel.o \
		moc_paginaweb.o \
		moc_mailing.o \
		moc_sqlquerymodel.o \
		moc_acercade.o \
		moc_usuarios.o \
		moc_buscarou.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_NetworkManagerQt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		GrxMenu.pro botonera/botonera.h \
		configuracion/configuracion.h \
		soporte/nmap_xml.h \
		sedes/sedes.h \
		soporte/soporte.h \
		soporte/equipos.h \
		soporte/ejecutahilo.h \
		soporte/tabescaner.h \
		basedatos/basedatos.h \
		mame/mame.h \
		usuarios/hilousuarios.h \
		usuarios/form_usuarios.h \
		usuarios/ldap.h \
		usuarios/clase_ldap.h \
		usuarios/usuario.h \
		usuarios/form_grupos.h \
		configuracion/simplecrypt.h \
		tunel.h \
		lib/lib.h \
		lib/globals.h \
		soporte/paginaweb.h \
		mailing/mailing.h \
		mailing/sqlquerymodel.h \
		acercade/acercade.h \
		soporte/usuarios.h \
		configuracion/buscarou.h main.cpp \
		botonera/botonera.cpp \
		configuracion/configuracion.cpp \
		soporte/nmap_xml.cpp \
		sedes/sedes.cpp \
		soporte/soporte.cpp \
		soporte/equipos.cpp \
		soporte/ejecutahilo.cpp \
		soporte/tabescaner.cpp \
		basedatos/basedatos.cpp \
		mame/mame.cpp \
		usuarios/hilousuarios.cpp \
		usuarios/clase_ldap.cpp \
		usuarios/usuario.cpp \
		usuarios/form_grupos.cpp \
		usuarios/form_usuarios.cpp \
		configuracion/simplecrypt.cpp \
		tunel.cpp \
		lib/lib.cpp \
		lib/globals.cpp \
		soporte/paginaweb.cpp \
		mailing/mailing.cpp \
		mailing/sqlquerymodel.cpp \
		acercade/acercade.cpp \
		soporte/usuarios.cpp \
		configuracion/buscarou.cpp
QMAKE_TARGET  = GrxMenu
DESTDIR       = 
TARGET        = GrxMenu


first: all
####### Build rules

$(TARGET): ui_botonera.h ui_configuracion.h ui_sedes.h ui_soporte.h ui_equipos.h ui_basedatos.h ui_mame.h ui_form_usuarios.h ui_form_grupos.h ui_paginaweb.h ui_mailing.h ui_acercade.h ui_usuarios.h ui_buscarou.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GrxMenu.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_NetworkManagerQt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		GrxMenu.pro \
		iconos.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5WebEngineWidgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5PrintSupport.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Quick.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Sql.prl \
		/usr/lib/x86_64-linux-gnu/libQt5WebChannel.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Qml.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Positioning.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile GrxMenu.pro -spec linux-g++
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_NetworkManagerQt.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
GrxMenu.pro:
iconos.qrc:
/usr/lib/x86_64-linux-gnu/libQt5WebEngineWidgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5PrintSupport.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.prl:
/usr/lib/x86_64-linux-gnu/libQt5Quick.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Sql.prl:
/usr/lib/x86_64-linux-gnu/libQt5WebChannel.prl:
/usr/lib/x86_64-linux-gnu/libQt5Qml.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5Positioning.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile GrxMenu.pro -spec linux-g++

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents iconos.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents botonera/botonera.h configuracion/configuracion.h soporte/nmap_xml.h sedes/sedes.h soporte/soporte.h soporte/equipos.h soporte/ejecutahilo.h soporte/tabescaner.h basedatos/basedatos.h mame/mame.h usuarios/hilousuarios.h usuarios/form_usuarios.h usuarios/ldap.h usuarios/clase_ldap.h usuarios/usuario.h usuarios/form_grupos.h configuracion/simplecrypt.h tunel.h lib/lib.h lib/globals.h soporte/paginaweb.h mailing/mailing.h mailing/sqlquerymodel.h acercade/acercade.h soporte/usuarios.h configuracion/buscarou.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp botonera/botonera.cpp configuracion/configuracion.cpp soporte/nmap_xml.cpp sedes/sedes.cpp soporte/soporte.cpp soporte/equipos.cpp soporte/ejecutahilo.cpp soporte/tabescaner.cpp basedatos/basedatos.cpp mame/mame.cpp usuarios/hilousuarios.cpp usuarios/clase_ldap.cpp usuarios/usuario.cpp usuarios/form_grupos.cpp usuarios/form_usuarios.cpp configuracion/simplecrypt.cpp tunel.cpp lib/lib.cpp lib/globals.cpp soporte/paginaweb.cpp mailing/mailing.cpp mailing/sqlquerymodel.cpp acercade/acercade.cpp soporte/usuarios.cpp configuracion/buscarou.cpp $(DISTDIR)/
	$(COPY_FILE) --parents botonera/botonera.ui configuracion/configuracion.ui sedes/sedes.ui soporte/soporte.ui soporte/equipos.ui basedatos/basedatos.ui mame/mame.ui usuarios/form_usuarios.ui usuarios/form_grupos.ui soporte/paginaweb.ui mailing/mailing.ui acercade/acercade.ui soporte/usuarios.ui configuracion/buscarou.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_iconos.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_iconos.cpp
qrc_iconos.cpp: iconos.qrc \
		/usr/lib/qt5/bin/rcc \
		imagenes/iconos/equipos/hardware.png \
		imagenes/iconos/equipos/config_pam.png \
		imagenes/iconos/equipos/download.png \
		imagenes/iconos/equipos/network-share-icon_35.png \
		imagenes/iconos/equipos/vnc.jpeg \
		imagenes/iconos/equipos/network-share-icon.png \
		imagenes/iconos/equipos/administrador.png \
		imagenes/iconos/equipos/update.png \
		imagenes/iconos/equipos/cronos.png \
		imagenes/iconos/equipos/lspci.png \
		imagenes/iconos/equipos/fortigate.jpg \
		imagenes/iconos/equipos/procesos.png \
		imagenes/iconos/equipos/asistencia.png \
		imagenes/iconos/equipos/telnet.jpeg \
		imagenes/iconos/equipos/mount.png \
		imagenes/iconos/equipos/info_equipo.png \
		imagenes/iconos/equipos/correo.png \
		imagenes/iconos/equipos/carpeta_personal.png \
		imagenes/iconos/equipos/instala.png \
		imagenes/iconos/equipos/net.png \
		imagenes/iconos/equipos/cups32.png \
		imagenes/iconos/equipos/glpi.png \
		imagenes/iconos/equipos/discos.png \
		imagenes/iconos/equipos/web.jpeg \
		imagenes/iconos/equipos/lscpu.png \
		imagenes/iconos/equipos/lsmod.png \
		imagenes/iconos/equipos/info.png \
		imagenes/iconos/equipos/clamav.png \
		imagenes/iconos/equipos/atalaya.png \
		imagenes/iconos/equipos/lsusb.png \
		imagenes/iconos/equipos/firewall.png \
		imagenes/iconos/equipos/cifrar.png \
		imagenes/iconos/equipos/ssh_35.png \
		imagenes/iconos/equipos/captura.png \
		imagenes/iconos/equipos/konekta.png \
		imagenes/iconos/equipos/mensaje.png \
		imagenes/iconos/equipos/conexiones_red.png \
		imagenes/iconos/equipos/ssh.png \
		imagenes/iconos/equipos/escaner.png \
		imagenes/iconos/equipos/lsblk.png \
		imagenes/iconos/usuarios/actualiza_usuario.png \
		imagenes/iconos/usuarios/actualiza_usuarios.png \
		imagenes/iconos/soporte/aytos.png \
		imagenes/iconos/soporte/portafirmas.png \
		imagenes/iconos/soporte/escoba.svg \
		imagenes/iconos/soporte/Desconocido_pc.png \
		imagenes/iconos/soporte/Windows_pc.png \
		imagenes/iconos/soporte/Printer.png \
		imagenes/iconos/soporte/gtablon.png \
		imagenes/iconos/soporte/buscando.gif \
		imagenes/iconos/soporte/memoria.jpeg \
		imagenes/iconos/soporte/guadaltel.png \
		imagenes/iconos/soporte/ISL50x50.png \
		imagenes/iconos/soporte/perfilcontratante.png \
		imagenes/iconos/soporte/moad.png \
		imagenes/iconos/soporte/Router.png \
		imagenes/iconos/soporte/linphone.png \
		imagenes/iconos/soporte/fortigate.png \
		imagenes/iconos/soporte/impresora.png \
		imagenes/iconos/soporte/Linux_pc.png \
		imagenes/iconos/soporte/epol.png \
		imagenes/iconos/soporte/atalaya.png \
		imagenes/iconos/soporte/citrix.png \
		imagenes/iconos/soporte/listin.jpeg \
		imagenes/iconos/basedatos/mailing.png \
		imagenes/iconos/basedatos/csv.png \
		imagenes/iconos/sedes/color.png \
		imagenes/iconos/botonera/nmap.png \
		imagenes/iconos/botonera/link.png \
		imagenes/iconos/botonera/online-96x96.png \
		imagenes/iconos/botonera/color.png \
		imagenes/iconos/botonera/ocs.png \
		imagenes/iconos/botonera/ISL.png \
		imagenes/iconos/botonera/sedes.png \
		imagenes/iconos/botonera/equipos.png \
		imagenes/iconos/botonera/virt-manager-icon.png \
		imagenes/iconos/botonera/listin.png \
		imagenes/iconos/botonera/cronos.png \
		imagenes/iconos/botonera/update.png \
		imagenes/iconos/botonera/asistencia.png \
		imagenes/iconos/botonera/mame.png \
		imagenes/iconos/botonera/WebMail.png \
		imagenes/iconos/botonera/salida.png \
		imagenes/iconos/botonera/usuario_on.png \
		imagenes/iconos/botonera/ISL50x50.png \
		imagenes/iconos/botonera/usuario_off.png \
		imagenes/iconos/botonera/segundo_plano.png \
		imagenes/iconos/botonera/moad.png \
		imagenes/iconos/botonera/Router.png \
		imagenes/iconos/botonera/AD.png \
		imagenes/iconos/botonera/beiro_cartera.png \
		imagenes/iconos/botonera/Linux_pc.png \
		imagenes/iconos/botonera/veleta.png \
		imagenes/iconos/botonera/300px-Granada_-_Mapa_municipal.svg.png \
		imagenes/iconos/botonera/lupa.png \
		imagenes/iconos/botonera/glpi.png \
		imagenes/iconos/botonera/usuario.png \
		imagenes/iconos/botonera/app.png \
		imagenes/iconos/botonera/logo.png \
		imagenes/iconos/botonera/atalaya.png \
		imagenes/iconos/botonera/Printer_pc.png \
		imagenes/iconos/botonera/sql.svg \
		imagenes/iconos/botonera/usuarios.png \
		imagenes/iconos/AcercaDe/GNU_and_Tux.svg
	/usr/lib/qt5/bin/rcc -name iconos iconos.qrc -o qrc_iconos.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -fpermissive -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_botonera.cpp moc_configuracion.cpp moc_sedes.cpp moc_soporte.cpp moc_equipos.cpp moc_ejecutahilo.cpp moc_tabescaner.cpp moc_basedatos.cpp moc_mame.cpp moc_hilousuarios.cpp moc_form_usuarios.cpp moc_form_grupos.cpp moc_tunel.cpp moc_paginaweb.cpp moc_mailing.cpp moc_sqlquerymodel.cpp moc_acercade.cpp moc_usuarios.cpp moc_buscarou.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_botonera.cpp moc_configuracion.cpp moc_sedes.cpp moc_soporte.cpp moc_equipos.cpp moc_ejecutahilo.cpp moc_tabescaner.cpp moc_basedatos.cpp moc_mame.cpp moc_hilousuarios.cpp moc_form_usuarios.cpp moc_form_grupos.cpp moc_tunel.cpp moc_paginaweb.cpp moc_mailing.cpp moc_sqlquerymodel.cpp moc_acercade.cpp moc_usuarios.cpp moc_buscarou.cpp
moc_botonera.cpp: configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		usuarios/usuario.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		lib/globals.h \
		acercade/acercade.h \
		tunel.h \
		libssh2_config.h \
		botonera/botonera.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/alberto/git/GrxMenu -I/lib -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include botonera/botonera.h -o moc_botonera.cpp

moc_configuracion.cpp: configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		usuarios/usuario.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		lib/globals.h \
		configuracion/configuracion.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/alberto/git/GrxMenu -I/lib -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include configuracion/configuracion.h -o moc_configuracion.cpp

moc_sedes.cpp: lib/lib.h \
		soporte/nmap_xml.h \
		configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		usuarios/usuario.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/globals.h \
		sedes/sedes.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/alberto/git/GrxMenu -I/lib -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include sedes/sedes.h -o moc_sedes.cpp

moc_soporte.cpp: lib/lib.h \
		soporte/nmap_xml.h \
		soporte/soporte.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/alberto/git/GrxMenu -I/lib -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include soporte/soporte.h -o moc_soporte.cpp

moc_equipos.cpp: soporte/nmap_xml.h \
		configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		usuarios/usuario.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		lib/globals.h \
		soporte/equipos.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/alberto/git/GrxMenu -I/lib -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include soporte/equipos.h -o moc_equipos.cpp

moc_ejecutahilo.cpp: soporte/nmap_xml.h \
		soporte/ejecutahilo.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/alberto/git/GrxMenu -I/lib -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include soporte/ejecutahilo.h -o moc_ejecutahilo.cpp

moc_tabescaner.cpp: soporte/nmap_xml.h \
		soporte/equipos.h \
		configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		usuarios/usuario.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		lib/globals.h \
		soporte/tabescaner.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/alberto/git/GrxMenu -I/lib -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include soporte/tabescaner.h -o moc_tabescaner.cpp

moc_basedatos.cpp: usuarios/usuario.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		lib/globals.h \
		basedatos/basedatos.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/alberto/git/GrxMenu -I/lib -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include basedatos/basedatos.h -o moc_basedatos.cpp

moc_mame.cpp: mame/mame.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/alberto/git/GrxMenu -I/lib -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mame/mame.h -o moc_mame.cpp

moc_hilousuarios.cpp: usuarios/form_usuarios.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		usuarios/usuario.h \
		ui_form_usuarios.h \
		configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		lib/globals.h \
		usuarios/form_grupos.h \
		usuarios/hilousuarios.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/alberto/git/GrxMenu -I/lib -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include usuarios/hilousuarios.h -o moc_hilousuarios.cpp

moc_form_usuarios.cpp: usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		usuarios/usuario.h \
		ui_form_usuarios.h \
		configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		lib/globals.h \
		usuarios/form_grupos.h \
		usuarios/form_usuarios.h \
		usuarios/form_usuarios.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/alberto/git/GrxMenu -I/lib -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include usuarios/form_usuarios.h -o moc_form_usuarios.cpp

moc_form_grupos.cpp: usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		usuarios/usuario.h \
		usuarios/form_usuarios.h \
		ui_form_usuarios.h \
		configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		lib/globals.h \
		usuarios/form_grupos.h \
		usuarios/form_grupos.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/alberto/git/GrxMenu -I/lib -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include usuarios/form_grupos.h -o moc_form_grupos.cpp

moc_tunel.cpp: configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		usuarios/usuario.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		lib/globals.h \
		libssh2_config.h \
		tunel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/alberto/git/GrxMenu -I/lib -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include tunel.h -o moc_tunel.cpp

moc_paginaweb.cpp: soporte/paginaweb.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/alberto/git/GrxMenu -I/lib -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include soporte/paginaweb.h -o moc_paginaweb.cpp

moc_mailing.cpp: mailing/sqlquerymodel.h \
		mailing/mailing.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/alberto/git/GrxMenu -I/lib -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mailing/mailing.h -o moc_mailing.cpp

moc_sqlquerymodel.cpp: mailing/sqlquerymodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/alberto/git/GrxMenu -I/lib -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mailing/sqlquerymodel.h -o moc_sqlquerymodel.cpp

moc_acercade.cpp: acercade/acercade.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/alberto/git/GrxMenu -I/lib -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include acercade/acercade.h -o moc_acercade.cpp

moc_usuarios.cpp: soporte/usuarios.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/alberto/git/GrxMenu -I/lib -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include soporte/usuarios.h -o moc_usuarios.cpp

moc_buscarou.cpp: configuracion/buscarou.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/alberto/git/GrxMenu -I/lib -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include configuracion/buscarou.h -o moc_buscarou.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_botonera.h ui_configuracion.h ui_sedes.h ui_soporte.h ui_equipos.h ui_basedatos.h ui_mame.h ui_form_usuarios.h ui_form_grupos.h ui_paginaweb.h ui_mailing.h ui_acercade.h ui_usuarios.h ui_buscarou.h
compiler_uic_clean:
	-$(DEL_FILE) ui_botonera.h ui_configuracion.h ui_sedes.h ui_soporte.h ui_equipos.h ui_basedatos.h ui_mame.h ui_form_usuarios.h ui_form_grupos.h ui_paginaweb.h ui_mailing.h ui_acercade.h ui_usuarios.h ui_buscarou.h
ui_botonera.h: botonera/botonera.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic botonera/botonera.ui -o ui_botonera.h

ui_configuracion.h: configuracion/configuracion.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic configuracion/configuracion.ui -o ui_configuracion.h

ui_sedes.h: sedes/sedes.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic sedes/sedes.ui -o ui_sedes.h

ui_soporte.h: soporte/soporte.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic soporte/soporte.ui -o ui_soporte.h

ui_equipos.h: soporte/equipos.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic soporte/equipos.ui -o ui_equipos.h

ui_basedatos.h: basedatos/basedatos.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic basedatos/basedatos.ui -o ui_basedatos.h

ui_mame.h: mame/mame.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic mame/mame.ui -o ui_mame.h

ui_form_usuarios.h: usuarios/form_usuarios.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic usuarios/form_usuarios.ui -o ui_form_usuarios.h

ui_form_grupos.h: usuarios/form_grupos.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic usuarios/form_grupos.ui -o ui_form_grupos.h

ui_paginaweb.h: soporte/paginaweb.ui \
		/usr/lib/qt5/bin/uic \
		/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets/QWebEngineView
	/usr/lib/qt5/bin/uic soporte/paginaweb.ui -o ui_paginaweb.h

ui_mailing.h: mailing/mailing.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic mailing/mailing.ui -o ui_mailing.h

ui_acercade.h: acercade/acercade.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic acercade/acercade.ui -o ui_acercade.h

ui_usuarios.h: soporte/usuarios.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic soporte/usuarios.ui -o ui_usuarios.h

ui_buscarou.h: configuracion/buscarou.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic configuracion/buscarou.ui -o ui_buscarou.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp botonera/botonera.h \
		configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		usuarios/usuario.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		lib/globals.h \
		acercade/acercade.h \
		tunel.h \
		libssh2_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

botonera.o: botonera/botonera.cpp botonera/botonera.h \
		configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		usuarios/usuario.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		lib/globals.h \
		acercade/acercade.h \
		tunel.h \
		libssh2_config.h \
		ui_botonera.h \
		soporte/soporte.h \
		soporte/nmap_xml.h \
		sedes/sedes.h \
		soporte/equipos.h \
		mame/mame.h \
		usuarios/form_usuarios.h \
		ui_form_usuarios.h \
		usuarios/form_grupos.h \
		mailing/mailing.h \
		mailing/sqlquerymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o botonera.o botonera/botonera.cpp

configuracion.o: configuracion/configuracion.cpp configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		usuarios/usuario.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		lib/globals.h \
		ui_configuracion.h \
		configuracion/buscarou.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configuracion.o configuracion/configuracion.cpp

nmap_xml.o: soporte/nmap_xml.cpp soporte/nmap_xml.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nmap_xml.o soporte/nmap_xml.cpp

sedes.o: sedes/sedes.cpp sedes/sedes.h \
		lib/lib.h \
		soporte/nmap_xml.h \
		configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		usuarios/usuario.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/globals.h \
		ui_sedes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sedes.o sedes/sedes.cpp

soporte.o: soporte/soporte.cpp soporte/soporte.h \
		lib/lib.h \
		soporte/nmap_xml.h \
		ui_soporte.h \
		soporte/equipos.h \
		configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		usuarios/usuario.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/globals.h \
		soporte/tabescaner.h \
		soporte/usuarios.h \
		soporte/ejecutahilo.h \
		soporte/paginaweb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o soporte.o soporte/soporte.cpp

equipos.o: soporte/equipos.cpp soporte/equipos.h \
		soporte/nmap_xml.h \
		configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		usuarios/usuario.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		lib/globals.h \
		ui_equipos.h \
		soporte/usuarios.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o equipos.o soporte/equipos.cpp

ejecutahilo.o: soporte/ejecutahilo.cpp soporte/ejecutahilo.h \
		soporte/nmap_xml.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ejecutahilo.o soporte/ejecutahilo.cpp

tabescaner.o: soporte/tabescaner.cpp soporte/tabescaner.h \
		soporte/nmap_xml.h \
		soporte/equipos.h \
		configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		usuarios/usuario.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		lib/globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tabescaner.o soporte/tabescaner.cpp

basedatos.o: basedatos/basedatos.cpp basedatos/basedatos.h \
		usuarios/usuario.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		lib/globals.h \
		ui_basedatos.h \
		tunel.h \
		configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		libssh2_config.h \
		soporte/nmap_xml.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o basedatos.o basedatos/basedatos.cpp

mame.o: mame/mame.cpp mame/mame.h \
		ui_mame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mame.o mame/mame.cpp

hilousuarios.o: usuarios/hilousuarios.cpp usuarios/hilousuarios.h \
		usuarios/form_usuarios.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		usuarios/usuario.h \
		ui_form_usuarios.h \
		configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		lib/globals.h \
		usuarios/form_grupos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hilousuarios.o usuarios/hilousuarios.cpp

clase_ldap.o: usuarios/clase_ldap.cpp usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		usuarios/usuario.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clase_ldap.o usuarios/clase_ldap.cpp

usuario.o: usuarios/usuario.cpp usuarios/usuario.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o usuario.o usuarios/usuario.cpp

form_grupos.o: usuarios/form_grupos.cpp usuarios/form_grupos.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		usuarios/usuario.h \
		usuarios/form_usuarios.h \
		ui_form_usuarios.h \
		configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		lib/globals.h \
		ui_form_grupos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o form_grupos.o usuarios/form_grupos.cpp

form_usuarios.o: usuarios/form_usuarios.cpp usuarios/form_usuarios.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		usuarios/usuario.h \
		ui_form_usuarios.h \
		configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		lib/globals.h \
		usuarios/form_grupos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o form_usuarios.o usuarios/form_usuarios.cpp

simplecrypt.o: configuracion/simplecrypt.cpp configuracion/simplecrypt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simplecrypt.o configuracion/simplecrypt.cpp

tunel.o: tunel.cpp tunel.h \
		configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		usuarios/usuario.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		lib/globals.h \
		libssh2_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tunel.o tunel.cpp

lib.o: lib/lib.cpp lib/lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lib.o lib/lib.cpp

globals.o: lib/globals.cpp lib/globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o globals.o lib/globals.cpp

paginaweb.o: soporte/paginaweb.cpp soporte/paginaweb.h \
		ui_paginaweb.h \
		lib/lib.h \
		configuracion/configuracion.h \
		configuracion/simplecrypt.h \
		basedatos/basedatos.h \
		usuarios/usuario.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o paginaweb.o soporte/paginaweb.cpp

mailing.o: mailing/mailing.cpp mailing/mailing.h \
		mailing/sqlquerymodel.h \
		ui_mailing.h \
		lib/lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mailing.o mailing/mailing.cpp

sqlquerymodel.o: mailing/sqlquerymodel.cpp mailing/sqlquerymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sqlquerymodel.o mailing/sqlquerymodel.cpp

acercade.o: acercade/acercade.cpp acercade/acercade.h \
		ui_acercade.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o acercade.o acercade/acercade.cpp

usuarios.o: soporte/usuarios.cpp soporte/usuarios.h \
		ui_usuarios.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o usuarios.o soporte/usuarios.cpp

buscarou.o: configuracion/buscarou.cpp configuracion/buscarou.h \
		ui_buscarou.h \
		usuarios/clase_ldap.h \
		usuarios/ldap.h \
		lib/lib.h \
		usuarios/usuario.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buscarou.o configuracion/buscarou.cpp

qrc_iconos.o: qrc_iconos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_iconos.o qrc_iconos.cpp

moc_botonera.o: moc_botonera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_botonera.o moc_botonera.cpp

moc_configuracion.o: moc_configuracion.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configuracion.o moc_configuracion.cpp

moc_sedes.o: moc_sedes.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sedes.o moc_sedes.cpp

moc_soporte.o: moc_soporte.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_soporte.o moc_soporte.cpp

moc_equipos.o: moc_equipos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_equipos.o moc_equipos.cpp

moc_ejecutahilo.o: moc_ejecutahilo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ejecutahilo.o moc_ejecutahilo.cpp

moc_tabescaner.o: moc_tabescaner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tabescaner.o moc_tabescaner.cpp

moc_basedatos.o: moc_basedatos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_basedatos.o moc_basedatos.cpp

moc_mame.o: moc_mame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mame.o moc_mame.cpp

moc_hilousuarios.o: moc_hilousuarios.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hilousuarios.o moc_hilousuarios.cpp

moc_form_usuarios.o: moc_form_usuarios.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_form_usuarios.o moc_form_usuarios.cpp

moc_form_grupos.o: moc_form_grupos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_form_grupos.o moc_form_grupos.cpp

moc_tunel.o: moc_tunel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tunel.o moc_tunel.cpp

moc_paginaweb.o: moc_paginaweb.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_paginaweb.o moc_paginaweb.cpp

moc_mailing.o: moc_mailing.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mailing.o moc_mailing.cpp

moc_sqlquerymodel.o: moc_sqlquerymodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sqlquerymodel.o moc_sqlquerymodel.cpp

moc_acercade.o: moc_acercade.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_acercade.o moc_acercade.cpp

moc_usuarios.o: moc_usuarios.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_usuarios.o moc_usuarios.cpp

moc_buscarou.o: moc_buscarou.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_buscarou.o moc_buscarou.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

